name: build

on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  DEPLOY_REGISTRY_URL: ${{ secrets.DEPLOY_REGISTRY_URL }}
  ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  build:
    name: build
    runs-on: [self-hosted, production]
    container:
      image: circleci/python:3.6.2
      env:
        TAP_POSTGRES_PORT: 5432
        TAP_POSTGRES_USER: test_user
        TAP_POSTGRES_PASSWORD: my-secret-passwd
        TAP_POSTGRES_HOST: test_postgres

    services:
      test_postgres:
        image: postgres:11.4
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: my-secret-passwd
          POSTGRES_DB: tap_postgres_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup virtual environment
        run: |
          python3 -m venv ./virtualenvs/tap-postgres
          . ./virtualenvs/tap-postgres/bin/activate
          pip install --upgrade pip setuptools
          pip install -e .[test]

      - name: Check dependencies for conflict
        run: |
          . ./virtualenvs/tap-postgres/bin/activate
          pip check && echo "No conflicts" || exit 1

      - name: Pylinting
        run: |
          . ./virtualenvs/tap-postgres/bin/activate
          pylint --rcfile .pylintrc --disable duplicate-code tap_postgres/

      - name: Tests
        run: |
          . ./virtualenvs/tap-postgres/bin/activate
          export LOGGING_CONF_FILE=./sample_logging.conf
          pytest --cov=tap_postgres  --cov-fail-under=59 tests -v

